### ISSUE TITLE
Перевод строки 0A

### ISSUE THREAD

**Issue by Mercury13** [symbl-cc/symbl-data#143]
Проворачивает барабан принтера на одну строку. На видеотерминале перемещает курсор вниз, прокручивая изображение, если надо. Сокращение — LF = Line Feed.

В азбуке Морзе использовался разделитель −•••− (мнемоника BT — Break Text). В первых телетайпах, работавших со скоростью в единицы бод, разделение управляющих символов на CR (возврат каретки) и LF (перевод строки) скрывало тот факт, что отведённая далеко вправо каретка могла и не успеть к появлению очередного символа (понятий «драйвер» и «буферизация» ещё не было).

Стандарт ASCII позволял перевод строк как через LF, так и через CR+LF. Большинство ОС форматировали текстовые файлы под все возможные устройства (отсюда CR+LF), зато ОС Multics (предок Unix) приняла LF.

В Си-подобных языках обозначается как \n — echo "one\ntwo";

В настоящее время LF используется как конец строки в текстовых файлах Unix, различных библиотеках родом с языка Си. В DOS/Windows стандартная библиотека Си при выводе в файл или на экран преобразует концы строк.

CR+LF используется в текстовых файлах DOS/Windows, в языках управления принтерами (это позволяет, например, печатать графику — барабан прокручивается не на строку, а на высоту печатающей головки), а также если концы строк должны гарантированно работать независимо от аппаратного и программного обеспечения.

Один CR используется в API Windows, библиотеках родом с языка Паскаль.

**Comment by asanov** [comment]
Добавлено
