### ISSUE TITLE
I would like to know if there is a way to contribute to translations for Unicode symbol fields or names.

### ISSUE THREAD

**Issue by infinitekh** [symbl-cc/symbl-data#159]
I came here by following the link from the https://symbl.cc/kr site.

In particular, it is very difficult to recognize as a Korean that the part related to ancient Chinese culture was transliterated into English and translated back into Korean, and it is better to translate directly from Chinese characters into Korean.

For example, the translation of 0x286A to 0x286f translates English as 'Yi Jing (Chinese: 易經, )', which seems to be a misuse of 'binary' to Koreans.

Since it is made with two symbols, yin, and yang, the translation that can be misread as 'binary' is not correct.

**Comment by asanov** [comment]
Hi, [infinitekh](https://github.com/infinitekh). You are more than welcome to contribute. Do it here: [https://github.com/unicode-table/symbl-data](https://github.com/unicode-table/symbl-data)

**Comment by asanov** [comment]
updated:
https://github.com/symbl-cc/symbl-data/
