### ISSUE TITLE
Maintenance status of the project regarding contributions

### ISSUE THREAD

**Issue by waldyrious** [symbl-cc/symbl-data#171]
In the past, I tried to submit improvements to the this repository, by adding related characters, which I find extremely useful when looking for certain characters. However, in one case [the PR](https://github.com/symbl-cc/symbl-data/pull/61/) took months before it got any response, and in the other case the [suggestion](https://github.com/symbl-cc/symbl-data/pull/94#issuecomment-458906194) I made for making the data easier to work with never got any response.

I'd like to know:
1. Is there an intent to be more responsive to community contributions like that moving forward, especially now that the project was rebranded?
2. Would a more readable data format for the related characters in [related.txt](https://github.com/symbl-cc/symbl-data/blob/master/data/related.txt) be considered?

**Comment by asanov** [comment]
1. Yes it is :) Sorry for our sluggishness
2. We are planning to do it
