### ISSUE TITLE
Roman numbers in Collections - Arabic Numerals 

### ISSUE THREAD

**Issue by jpachta** [symbl-cc/symbl-data#173]
There is big bug in the list of [Roman numbers](https://symbl.cc/en/collections/arabic-numerals/#sub-menu-link-0) starting with number **50** that should be letter "L" not "C" and all higher numbers then shifted do "C" is 100 etc.

Wrong on page: 
Ⅰ – 1 
Ⅴ – 5 
Ⅹ – 10 
Ⅽ – 50  <= wrong
Ⅾ — 100  <= wrong
Ⅿ — 500  <= wrong
ↁ — 1000  <= wrong

Correct is:
I – 1
V – 5
X – 10
L – 50
Ⅽ – 100
Ⅾ – 500
Ⅿ – 1000  

Well starting with 1000 and higher numbers can be used symbol of connected CD or cıɔ (as C, I, reversed C) that became converted into Unicode symbols...

See Wikipedia

-  Roman numerals section Unicode https://en.wikipedia.org/wiki/Roman_numerals 
   - and referred page Numerals in Unicode https://en.wikipedia.org/wiki/Numerals_in_Unicode#Roman_numerals

**Comment by alex-subb** [comment]
Fixed
