### ISSUE TITLE
Found an Mistake 

### ISSUE THREAD

**Issue by iloveganja** [symbl-cc/symbl-data#179]
![image](https://user-images.githubusercontent.com/64712699/235656134-0e98c327-8783-4501-8b0f-ef0bfe9ebd0b.png)

**Comment by iloveganja** [comment]
![2023-05-03- 1](https://user-images.githubusercontent.com/64712699/235903445-b003305b-77c2-4346-a36a-871c2b9fe2e1.png)

**Comment by asanov** [comment]
Done
