### ISSUE TITLE
What happened? Search broken.

### ISSUE THREAD

**Issue by LiamK** [symbl-cc/symbl-data#180]
The old site was so useful, and now this!
The main problem is that the search feature doesn't work.
Even going to the old site, it doesn't work.
It's unusable.
Also, don't need cookies.  At least get rid of the popup at the bottom for those who reject them.

**Comment by asanov** [comment]
We're sorry for the inconvenience with our search feature. Our team is already working on a fix. We appreciate your patience.

**Comment by asanov** [comment]
Fixed
