### ISSUE TITLE
The Search bar functional stopped properly working

### ISSUE THREAD

**Issue by voltel** [symbl-cc/symbl-data#185]
🐛  When entering a search phrase into the Search bar in Firefox, the interface doesn't produce a list of options. Major issue, as it renders the site unusable.

**Comment by MarcCMcC** [comment]
The search bar only returns results for exact character matches:  i.e.  ["◈"](https://symbl.cc/en/search/?q=%E2%97%88)  or  ["★"](https://symbl.cc/en/search/?q=%E2%98%85).
It fails to return any matches for:  [exact names](https://symbl.cc/en/search/?q=White+Diamond+Containing+Black+Small+Diamond),  or [phrases / words in the character descriptions](https://symbl.cc/en/search/?q=Small),  or the [auto-populated  "popular searches"  terms](https://symbl.cc/en/search/?q=Heart+symbols) that appear when the search bar is active for text entry.

The [old version's](https://old.unicode-table.com/en/) search bar is also broken with the same behavior as the main site  (Searching for:  ["◈"](https://old.unicode-table.com/en/search/?q=%E2%97%88)  returns only a single exact match,  but searching for:  [White Diamond Containing Black Small Diamond](https://old.unicode-table.com/en/search/?q=White+Diamond+Containing+Black+Small+Diamond)  fails to return any results.)

**Comment by asanov** [comment]
Fixed

**Comment by waldyrious** [comment]
@asanov can the fix be applied to the old version as well? Or should there be a separate issue for that?
