### ISSUE TITLE
Unable to search symbol as "S with" format

### ISSUE THREAD

**Issue by ZhuGeKongBo** [symbl-cc/symbl-data#191]
New version only match full word, Fuzzy search is no longer supported, which is a very bad change

**Comment by harbanero5** [comment]
> New version only match full word, Fuzzy search is no longer supported, which is a very bad change

Spam phising[https://calendly.com/bal12p5o/one-on-one-with-me]()

**Comment by Zhorau** [comment]
> New version only match full word, Fuzzy search is no longer supported, which is a very bad change

Yes, I now use other resources to find HTML codes, because this resource has become completely inconvenient to use.

**Comment by asanov** [comment]
Done
