### ISSUE TITLE
In case it helps, I'd be happy to help review changes to the Portuguese translation.

### ISSUE THREAD

**Issue by harbanero5** [symbl-cc/symbl-data#192]
In case it helps, I'd be happy to help review changes to the Portuguese translation.

_Originally posted by @waldyrious in https://github.com/symbl-cc/symbl-data/issues/183#issuecomment-1578738055_

**Comment by harbanero5** [comment]
@LIttleAncientForestKami @waldyrious

**Comment by harbanero5** [comment]
@waldyrious @vasa-c

**Comment by LIttleAncientForestKami** [comment]
@harbanero5 can't help with this, sorry.

**Comment by alex-subb** [comment]
> ```
>           In case it helps, I'd be happy to help review changes to the Portuguese translation.
> ```
> 
> 
>     
>   
> 
> _Originally posted by @waldyrious in [#183 (comment)](https://github.com/symbl-cc/symbl-data/issues/183#issuecomment-1578738055)_

Hello! Can you send your contacts to cc@symbl.cc?
