### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by mpfaff** [symbl-cc/symbl-data#193]
Searching for most terms results in `No results for “<TERM>”`. For example "overline", or "Overline" do not work, but "203E" works just fine.

Other terms result in `Search results on demand “<TERM>”: 1`. For example, "checkmark". Change to "check mark" and you get lots of results, **except** for the "Check Mark" character (`U+2713`)).

Some searches work, but seems to only those that match other attributes of the characters, or names of sets. Strangely, it seems like one word might be used only for filtering by set?

- "box" turns up the "Box Drawing" set, but no characters within the set.
- "check mark" turns up many characters, and some sets, but not the "Check Mark" character (`U+2713`)
- "check check mark" turns up a bunch of check mark characters, including the aforementioned one.
- So does "check check"
- And "foo check"
- And "check foo" ("check foo" but not "check mark", really?)
- But not "check"

**Comment by asanov** [comment]
We are working to fix it

**Comment by asanov** [comment]
fixed
