### ISSUE TITLE
Типографские правки кода сайта

### ISSUE THREAD

**Issue by WilliamTokarev** [symbl-cc/symbl-data#195]
1) В таких местах, как `т. д.`, `н. э.`, `до н. э.` и пр. нужно ставить неразрывный пробел. Например: `до&nbsp;н.&nbsp;э.`. Это улучшит восприятие написанного.
2) Лишний пробел между словом и запятой (точкой). Пример: `создана до [кириллицы](https://symbl.cc/ru/unicode/blocks/cyrillic/) , а та`. Это имеет место, если перед знаком препинания стоит слово-ссылка.
3) Не забывайте букву `ё`! Примеры: `Белые и черные стрелки`, `Звездочки и астериски` и пр.
4) Не забываем длинное тире `—`! Пример: `этих символов (U+1F100-у+1F1FF)` (нужно `U+1F100—U+1F1FF`) и что это за `у+` (вместо `U+`)?
5) Не забываем скобки-ёлочки `«»`! Пример: `Компоненты символа "обрезка"` (нужно `«обрезка»`).
6) Есть ошибки в словах. Где видел, не помню. Но, что есть, это точно!

**Comment by WilliamTokarev** [comment]
По пункту 5. Примеров можно привести много. Вот один из них: https://symbl.cc/ru/unicode/blocks/miscellaneous-symbols
Листаем вниз и находим вот такой подраздел `"И цзин" или "Чжоу И" ("Книга Перемен")`

**Comment by WilliamTokarev** [comment]
По пункту 4. Это найдено здесь:https://symbl.cc/ru/unicode/blocks/enclosed-alphanumerics
В подразделе описания («Больше информации»).

**Comment by WilliamTokarev** [comment]
По пункту 4. Вновь примеров можно привести много. Вот один из них: https://symbl.cc/ru/unicode/blocks/glagolitic
В подразделе описания, второй параграф, первое предложение: `Целый ряд фактов указывает на то, что глаголица была создана до [кириллицы](https://symbl.cc/ru/unicode/blocks/cyrillic/) , а та в свою очередь создавалась на базе глаголицы и [греческого алфавита](https://symbl.cc/ru/unicode/blocks/greek-coptic/) .` Визуально (сам посмотри в браузере, ибо как вставить сюда фото, я не знаю) запятая отделена от слова `кириллицы` и в конце предложения точка отделена от слова `алфавита`. Т.к. физически пробела там нет, то всё дело в заданных свойствах тэга `span` в CSS, а именно `span.ml-set`.

**Comment by alex-subb** [comment]
@WilliamTokarev думаю сможем поправить в ближайших релизах. Касательно кавычек напишу отдельно - они проработаны в текстах, но заголовков мы не касались.

**Comment by WilliamTokarev** [comment]
Вот пример оформления ссылки в CSS (достаточно красиво выглядит):
`a, a:visited, a:focus		{ outline: none; text-decoration: none; color: #0000FF; }
a:hover				{ color: #DF00DF; }
a.owner, a.owner:visited	{ text-decoration: none; color: #D08060; }
a.owner:hover			{ color: #DF00DF; }
a.main, a.main:visited		{ text-decoration: none; color: #c04020; }
a.main:hover			{ color: #DF00DF; }
a.news, a.news:visited		{ text-decoration: none; color: #4020a0; }
a.news:hover			{ color: #DF00DF; }`

**Comment by WilliamTokarev** [comment]
Да, ещё. Блок «Египетские иероглифы» https://symbl.cc/ru/unicode/blocks/egyptian-hieroglyphs
Возьмём пример описания иероглифа `A001` https://symbl.cc/ru/13000. В заголовке и в самом тексте описания стоит код иероглифа `a001`. Это не правильно! Все группы иероглифов (по Гардинеру) пишутся с заглавной буквы (кроме группы `Aa`). Но в коде иероглифов группа состоит из вех заглавных букв! Например: A001, K001, W001A, NL020 и AA001.
См.: https://www.unicode.org/charts/PDF/U13000.pdf

**Comment by WilliamTokarev** [comment]
И ещё. Сокращения `т. д.` и `т. п.` следует писать с пробелом. В коде нужно ставить неразрывный пробел. Вот так: `т.&nbsp;д.` и `т.&nbsp;п.`. Это можно поправить простой заменой в коде.
Пример: https://symbl.cc/ru/unicode/blocks/egyptian-hieroglyphs, `O. Здания, их составляющие и т.п.`

**Comment by WilliamTokarev** [comment]
> По пункту 4. Вновь примеров можно привести много. Вот один из них: https://symbl.cc/ru/unicode/blocks/glagolitic В подразделе описания, второй параграф, первое предложение: `Целый ряд фактов указывает на то, что глаголица была создана до [кириллицы](https://symbl.cc/ru/unicode/blocks/cyrillic/) , а та в свою очередь создавалась на базе глаголицы и [греческого алфавита](https://symbl.cc/ru/unicode/blocks/greek-coptic/) .` Визуально (сам посмотри в браузере, ибо как вставить сюда фото, я не знаю) запятая отделена от слова `кириллицы` и в конце предложения точка отделена от слова `алфавита`. Т.к. физически пробела там нет, то всё дело в заданных свойствах тэга `span` в CSS, а именно `span.ml-set`. Это конечно же не ошибка, но выглядит неприятно… Да, только заметил! Пример можно увидеть прямо в этом сообщении! Посмотри как отделена точка от `слова`. Здесь хорошо видно, как точка отделена (это всё CSS, а именно тэг `code`, но это, конечно, не касается сайта `symbl.cc`). Моё предложение: может ссылки в тексте выделять не серым подчёркиванием, а цветом?

**Comment by WilliamTokarev** [comment]
Большое спасибо! Приятно видеть, как сайт постепенно усовершенствуется! Особая благодарность за правку отступов перед запятой/точкой после ссылок! Может ссылки всё же выделять цветом, а не серым подчёркиванием? Мне кажется так бы выглядело лучше, да и более наглядно.
