### ISSUE TITLE
Почему-то неверно отображается символ для копирования

### ISSUE THREAD

**Issue by DavidSargsyan1991** [symbl-cc/symbl-data#200]
https://i.imgur.com/nsYu6AH.png

**Comment by asanov** [comment]
Давид, при копировании отображается то, как выглядит символ в вашем системный шрифте. На сайте для иллюстрации символов используется наш собственный шрифт и картинки Эмоджи Apple. На странице символа во вкладке Платформы можно увидеть, как отображается конкретный эмоджи на разных платформах (win, mac итд)
