### ISSUE TITLE
[bug] Search is not working

### ISSUE THREAD

**Issue by danfmaia** [symbl-cc/symbl-data#208]
It's simply not working. It's always bringing no results. It happens both on web and mobile.

<img src="https://github.com/symbl-cc/symbl-data/assets/14301888/1b2b8adc-40ca-40fd-b7eb-f95e03fa1aed" width="400">

**Comment by danfmaia** [comment]
The problem stopped happening, but no information was given.

**Comment by asanov** [comment]
Yes, it was fixed @danfmaia
